Class {
	#name : #GtSmaCCDefinitionsFilter,
	#superclass : #GtSearchTypedEntitiesFilter,
	#category : #'GT4SmaCC-Development-UI-Filters'
}

{ #category : #accessing }
GtSmaCCDefinitionsFilter class >> resultType [
	^ GtSmaCCDefinitionGroupResult
]

{ #category : #accessing }
GtSmaCCDefinitionsFilter >> highlighter [
	^ nil
]

{ #category : #accessing }
GtSmaCCDefinitionsFilter >> resultType [
	^ GtSmaCCDefinitionGroupResult
]
